### PR TITLE
Fix Edit Dialog target

### PR DESCRIPTION
**Pull request by pdore-netfore**
Use ```currentTarget``` instead of ```target```.

Fixes Issue #229

### CODE REVIEW

**Comment by daniel-nagy** [comment]
did you confirm that that worked?

**Comment by pdore-netfore** [comment]
Yup works for me.

**Comment by daniel-nagy** [comment]
Okay, I merged it. I'm in the middle of some car electrical issues. I'll create a release when I get home.

**Comment by pdore-netfore** [comment]
Thanks!

**Pull request merged**
