### PR TITLE
Update bower.json for support 1.0

### PR DESCRIPTION
**Pull request by idoo**

### CODE REVIEW

**Comment by cleever** [comment]
+1

Could @daniel-nagy or one of the contributors merge this ?

**Comment by JoshBargar** [comment]
+1, this seems to address the data bind issue others are having as well.

**Comment by vapits** [comment]
+1

**Comment by triniwiz** [comment]
+1

**Comment by idoo** [comment]
https://github.com/daniel-nagy/md-data-table/pull/193

**Comment by stefanahman** [comment]
Or this: https://github.com/daniel-nagy/md-data-table/pull/213

**Pull request closed without merging**
