### PR TITLE
add 'All' option for pagination

### PR DESCRIPTION
**Pull request by kelleysy**
Added the 'All' option for the pagination select menu after following up with your notes. 
Seeing if this can be added to the master, please let me know if I can change anything.

Thanks!

### CODE REVIEW

**Comment by daniel-nagy** [comment]
I think I would like to make this more generic so the developer can have arbitrary options and define the meaning of them. So when the user selects "All", the directive will evaluate the value.

```javascript
$scope.limitOptions = [5, 10, 15, {
  label: 'All',
  value: total // or function () {}
};
```

**Comment by kelleysy** [comment]
Do you mean something like this?

`  $scope.limitOptions = [5, 10, 15, {
    label: 'All',
    value: function () {
      return $scope.desserts.length;
    }
  }];`

**Comment by daniel-nagy** [comment]
Yeah, I would just evaluate the expression and make sure that it returns a number else ignore it.

**Comment by kelleysy** [comment]
How do you suggest I update the binding on the select menu? It shows 5, 10, 15, { label: 'All'} as the options. Would I write a function in the mdTablePagination.js as the limitOptions var?

**Comment by daniel-nagy** [comment]
I went ahead and implemented this. Checkout version `0.10.8`. :)

**Comment by kelleysy** [comment]
Thank you!!! :) 

:+1:

**Pull request closed without merging**
