### PR TITLE
changed how the onPaginate callback fn is bound

### PR DESCRIPTION
**Pull request by AodhanHayter**
Hey first off, thanks for writing these angular components been using them for a while with no issues but I did find a small improvement / issue. On the pagination component.

`<md-table-pagination></md-table-pagination>`

You can pass in a callback function as an attribute `md-on-paginate="myCallback"`

This works perfectly in your example application but it was causing problems for me when writing controllers as es6 classes. The problem was how the callback was bound to the directive.

```javascript
// directive bindings
// the problem is how the '=' and '&' differ in binding behavior
bindToController: {
  onPaginate: '=?mdOnPaginate', // was this way
  onPaginate: '&?mdOnPaginate' // I propose using this method of binding
}
```

This is the exact issue that PR #386 is related to as well, just a different callback function.
 
[Here's a good explanation of how the '&' binding works](https://thinkster.io/egghead/isolate-scope-am)
Ignore the link if you already know how it works.

Basically the issue I was having is that the callback function is being called within the directives controller context. This can cause issues when using controller as syntax if you need to use the 'this' reference in the callback function that gets passed to the directive. This can be avoided by using the '&' binding. 

Example:
```javascript
class MyController {
  constructor () {
    this.thing = 'thing'
  }

 getStuff (page, limit) {
    //do async stuff
   return 'data'
  }

  onPaginateCallback (page, limit) {
    // need reference to this controllers 'this' to be able to call this.getStuff
    // this would fail with the regular '=' binding due to 'this' being the directives controller at call time
    this.getStuff(page, limit)
    console.log(this.thing)
  }
}
```

Once again thanks for writing these components. If you have any questions or want any clarification shoot me a message.

### CODE REVIEW

**Comment by chrisgonzales** [comment]
Would really like this implemented, @AodhanHayter how did you get around this without using the above modifications. New to angular in general.

**Comment by AodhanHayter** [comment]
@chrisgonzales I'm using the above modification, not really sure if there's a way around it, you'd have to get creative. I'm using my own fork of this project at the moment. If this is causing problems for you I would suggest forking my fork. My fork has no other modifications, just this change.

**Comment by daniel-nagy** [comment]
If you are using Typescript or Babel experimental features you can use the following syntax

```Typescript
class MyClass {
  onPagination = (page, limit) => {
    this.foo = 'bar';
  }
}
```

If you're not using Typescript or you don't have Babel experimental features enabled you can define the method in the constructor.

```javascript
class MyClass {
  constructor() {
    this.onPagination = () => {
      this.foo = 'bar';
    }
  }
}
```

If you are using POJ just make an alias for `this`.

```javascript
function MyClass() {
  var self = this;
  
  self.onPagination = function (page, limit) {
    self.foo = 'bar';
  };
}
```

You can also use the bind method.

```javascript
function MyClass() {
  this.onPagination = function (page, limit) {
    this.foo = 'bar';
  }.bind(this);
}
```

**Comment by daniel-nagy** [comment]
The reason I didn't use `&` is because it creates an expression that is evaluated in the current context (scope). This means I can't simply call a method with the arguments `scope`, `limit`

```javascript
// pagination controller
self.onPaginate(self.page, self.limit);
```

instead I would need to pass a context

```javascript
self.onPaginate({page: self.page, limit: self.limit});
```

and the user's template would have to be 

```html
<md-table-pagination md-on-paginate="myCallback(page, limit)"></md-table-pagination>
```

Note that now the parameter names would need to match exactly, i.e. the following would not work.

```html
<md-table-pagination md-on-paginate="myCallback(one, two)"></md-table-pagination>
```

**Comment by AodhanHayter** [comment]
All perfectly good ways to skin this cat, don't know why I spaced on just using a `.bind(this)` or an arrow function. Guess it's just my preference to bind callbacks with '&' in angular.

The style really just boils down to.

Do you want to give the user **implicit** reference to the context the callback is defined in with '&', but then they have to be sure to pass the correct params to the callback in the template.

Or just pass the function and have the user state **explicitly** what context they want with a `.bind()` or any of the above solutions.

I would definitely defer the style judgment to the author @daniel-nagy

**Comment by chrisgonzales** [comment]
Thanks for the assitance, I ended up actually forking and applying AodhanHayter approach, i'm using es6 and new to angular. And in a time crunch to figure out another route. Thanks for all the work you've done.

**Pull request closed without merging**
