### PR TITLE
Issue #156 onSelect Event

### LINKED ISSUE #156: on-select event
I think that is necessary an event that is fired when an user click in selection checkbox.
Today I use ng-click inside <tr> to call a method. But when user check an item, ng-click was not triggered.

### PR DESCRIPTION
**Pull request by cleever**
Closes #156 

Add onSelectClick event to checkbox.

Usage: <tr on-select-click="method()"...

### CODE REVIEW

**Comment by Kajvdh** [comment]
+1 Thanks for sharing! Please merge

**Comment by brianfeister** [comment]
+1 ... Can we merge this please?

**Comment by RenatoRC** [comment]
+1... Merge this please. This feature is absolutely necessary.

**Comment by mruba** [comment]
merge this pleaasSEEE!

**Pull request closed without merging**
